name: Update KRX Stocks

on:

  schedule:
    - cron: '0 22 * * 0-4'

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python update_stock_list.py
        env:
          KRX_ID: ${{ secrets.KRX_ID }}
          KRX_PW: ${{ secrets.KRX_PW }}

      - name: Commit

        run: |

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add data/stocks.csv

          git diff --cached --quiet || \
          git commit -m "Auto update"

          git push
